"""add status to session

Revision ID: 0c13fde3643a
Revises: a1b2c3d4e5f6
Create Date: 2026-09-09 23:13:21.445916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c13fde3643a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_summarizer',
    sa.Column('raw_summarizer_id', sa.UUID(), nullable=False),
    sa.Column('raw_summarizer_timestamp', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_summarizer_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('raw_summarizer_id', 'raw_summarizer_timestamp')
    )
    op.alter_column('attendance_records', 'attendance_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('device_heartbeat', sa.Column('firmware_version', sa.String(), nullable=True))
    op.add_column('device_heartbeat', sa.Column('uptime', sa.BIGINT(), nullable=True))
    op.alter_column('occupancy', 'occupancy_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('room_sessions', sa.Column('session_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_room_sessions_session_status'), 'room_sessions', ['session_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_sessions_session_status'), table_name='room_sessions')
    op.drop_column('room_sessions', 'session_status')
    op.alter_column('occupancy', 'occupancy_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('device_heartbeat', 'uptime')
    op.drop_column('device_heartbeat', 'firmware_version')
    op.alter_column('attendance_records', 'attendance_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_table('raw_summarizer')
    # ### end Alembic commands ###
