"""create user table

Revision ID: 3f3d34ea40bf
Revises: 560716a1684b
Create Date: 2026-08-25 16:52:02.733918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f3d34ea40bf'
down_revision: Union[str, Sequence[str], None] = '560716a1684b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_state_source',
    sa.Column('emergency_state_source_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('emergency_state_source_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('emergency_state_source_id')
    )
    op.drop_index(op.f('room_event_room_event_timestamp_idx'), table_name='room_event')
    op.add_column('room_state', sa.Column('room_emergency_state_source_id', sa.BIGINT(), nullable=True))
    op.drop_index(op.f('room_state_room_state_timestamp_idx'), table_name='room_state')
    op.create_foreign_key(None, 'room_state', 'emergency_state_source', ['room_emergency_state_source_id'], ['emergency_state_source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_state', type_='foreignkey')
    op.create_index(op.f('room_state_room_state_timestamp_idx'), 'room_state', [sa.literal_column('room_state_timestamp DESC')], unique=False)
    op.drop_column('room_state', 'room_emergency_state_source_id')
    op.create_index(op.f('room_event_room_event_timestamp_idx'), 'room_event', [sa.literal_column('room_event_timestamp DESC')], unique=False)
    op.drop_table('emergency_state_source')
    # ### end Alembic commands ###
