"""add_door_smoke_state_models

Revision ID: 41f6e90c15cf
Revises: 3f3d34ea40bf
Create Date: 2026-08-26 14:36:22.279240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '41f6e90c15cf'
down_revision: Union[str, Sequence[str], None] = '3f3d34ea40bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_door_state',
    sa.Column('room_door_state_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('room_door_state_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('door_state', sa.Enum('LOCKED', 'UNLOCKED', name='doorstateenum'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('room_door_state_id', 'room_door_state_timestamp')
    )
    op.create_index(op.f('ix_room_door_state_door_state'), 'room_door_state', ['door_state'], unique=False)
    op.create_table('room_smoke_state',
    sa.Column('room_smoke_state_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('room_smoke_state_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('smoke_state', ENUM('NORMAL', 'SUSPECTED', 'EMERGENCY', name='smokestate', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('room_smoke_state_id', 'room_smoke_state_timestamp')
    )
    op.create_index(op.f('ix_room_smoke_state_smoke_state'), 'room_smoke_state', ['smoke_state'], unique=False)
    
    # Convert to TimescaleDB hypertables
    op.execute("SELECT create_hypertable('room_door_state', by_range('room_door_state_timestamp'), if_not_exists => TRUE)")
    op.execute("SELECT create_hypertable('room_smoke_state', by_range('room_smoke_state_timestamp'), if_not_exists => TRUE)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_smoke_state_smoke_state'), table_name='room_smoke_state')
    op.drop_table('room_smoke_state')
    op.drop_index(op.f('ix_room_door_state_door_state'), table_name='room_door_state')
    op.drop_table('room_door_state')
    # ### end Alembic commands ###
