"""fix_model_issues

Revision ID: 4d2736916ddc
Revises: 41f6e90c15cf
Create Date: 2026-09-02 11:08:24.086289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2736916ddc'
down_revision: Union[str, Sequence[str], None] = '41f6e90c15cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('command_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('command_type', sa.String(), nullable=False),
    sa.Column('command_value', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('command_id')
    )
    op.create_index(op.f('ix_command_device_id'), 'command', ['device_id'], unique=False)
    op.create_index(op.f('ix_command_room_id'), 'command', ['room_id'], unique=False)
    op.create_index(op.f('ix_command_status'), 'command', ['status'], unique=False)
    op.drop_index(op.f('ix_attendance_events_attendance_event_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_attendance_timestamp'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_gateway_received_timestamp'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_message_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_source_timestamp'), table_name='attendance_events')
    op.drop_constraint(op.f('attendance_events_card_uid_fkey'), 'attendance_events', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_statuses_attendance_status_id'), table_name='attendance_statuses')
    op.drop_index(op.f('ix_attendance_statuses_description'), table_name='attendance_statuses')
    op.drop_index(op.f('ix_attendance_statuses_status_name'), table_name='attendance_statuses')
    op.drop_index(op.f('ix_device_device_firmware_version'), table_name='device')
    op.drop_index(op.f('ix_device_device_id'), table_name='device')
    op.drop_index(op.f('ix_device_device_name'), table_name='device')
    op.drop_index(op.f('ix_device_last_seen_timestamp'), table_name='device')
    op.drop_index(op.f('ix_device_room_id'), table_name='device')
    op.create_index(op.f('ix_device_room_id'), 'device', ['room_id'], unique=False)
    op.drop_index(op.f('ix_device_heartbeat_device_heartbeat_id'), table_name='device_heartbeat')
    op.drop_index(op.f('ix_device_heartbeat_gateway_received_timestamp'), table_name='device_heartbeat')
    op.drop_index(op.f('ix_device_heartbeat_heartbeat_timestamp'), table_name='device_heartbeat')
    op.drop_index(op.f('ix_device_heartbeat_message_id'), table_name='device_heartbeat')
    op.drop_index(op.f('ix_device_heartbeat_source_timestamp'), table_name='device_heartbeat')
    op.drop_index(op.f('ix_device_status_device_id'), table_name='device_status')
    op.drop_index(op.f('ix_device_status_status_timestamp'), table_name='device_status')
    op.drop_index(op.f('ix_environment_air_quality'), table_name='environment')
    op.drop_index(op.f('ix_environment_co2'), table_name='environment')
    op.drop_index(op.f('ix_environment_environment_id'), table_name='environment')
    op.drop_index(op.f('ix_environment_environment_timestamp'), table_name='environment')
    op.drop_index(op.f('ix_environment_gateway_received_timestamp'), table_name='environment')
    op.drop_index(op.f('ix_environment_humidity'), table_name='environment')
    op.drop_index(op.f('ix_environment_message_id'), table_name='environment')
    op.drop_index(op.f('ix_environment_room_mode'), table_name='environment')
    op.drop_index(op.f('ix_environment_smoke_detected'), table_name='environment')
    op.drop_index(op.f('ix_environment_smoke_threshold'), table_name='environment')
    op.drop_index(op.f('ix_environment_smoke_value'), table_name='environment')
    op.drop_index(op.f('ix_environment_source_timestamp'), table_name='environment')
    op.drop_index(op.f('ix_environment_temperature'), table_name='environment')
    op.drop_index(op.f('ix_occupancy_gateway_received_timestamp'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_message_id'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_occupancy_count'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_occupancy_id'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_occupancy_timestamp'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_occupancy_type'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_source_timestamp'), table_name='occupancy')
    op.drop_index(op.f('ix_room_door_state_door_state'), table_name='room_door_state')
    op.drop_index(op.f('room_door_state_room_door_state_timestamp_idx'), table_name='room_door_state')
    op.create_index(op.f('ix_room_door_state_room_id'), 'room_door_state', ['room_id'], unique=False)
    op.drop_index(op.f('ix_room_event_room_mode'), table_name='room_event')
    op.create_index(op.f('ix_room_event_room_id'), 'room_event', ['room_id'], unique=False)
    op.drop_index(op.f('ix_room_smoke_state_smoke_state'), table_name='room_smoke_state')
    op.drop_index(op.f('room_smoke_state_room_smoke_state_timestamp_idx'), table_name='room_smoke_state')
    op.create_index(op.f('ix_room_smoke_state_room_id'), 'room_smoke_state', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_state_room_id'), 'room_state', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_state_room_id'), table_name='room_state')
    op.drop_index(op.f('ix_room_smoke_state_room_id'), table_name='room_smoke_state')
    op.create_index(op.f('room_smoke_state_room_smoke_state_timestamp_idx'), 'room_smoke_state', [sa.literal_column('room_smoke_state_timestamp DESC')], unique=False)
    op.create_index(op.f('ix_room_smoke_state_smoke_state'), 'room_smoke_state', ['smoke_state'], unique=False)
    op.drop_index(op.f('ix_room_event_room_id'), table_name='room_event')
    op.create_index(op.f('ix_room_event_room_mode'), 'room_event', ['room_mode'], unique=False)
    op.drop_index(op.f('ix_room_door_state_room_id'), table_name='room_door_state')
    op.create_index(op.f('room_door_state_room_door_state_timestamp_idx'), 'room_door_state', [sa.literal_column('room_door_state_timestamp DESC')], unique=False)
    op.create_index(op.f('ix_room_door_state_door_state'), 'room_door_state', ['door_state'], unique=False)
    op.create_index(op.f('ix_occupancy_source_timestamp'), 'occupancy', ['source_timestamp'], unique=False)
    op.create_index(op.f('ix_occupancy_occupancy_type'), 'occupancy', ['occupancy_type'], unique=False)
    op.create_index(op.f('ix_occupancy_occupancy_timestamp'), 'occupancy', ['occupancy_timestamp'], unique=False)
    op.create_index(op.f('ix_occupancy_occupancy_id'), 'occupancy', ['occupancy_id'], unique=False)
    op.create_index(op.f('ix_occupancy_occupancy_count'), 'occupancy', ['occupancy_count'], unique=False)
    op.create_index(op.f('ix_occupancy_message_id'), 'occupancy', ['message_id'], unique=False)
    op.create_index(op.f('ix_occupancy_gateway_received_timestamp'), 'occupancy', ['gateway_received_timestamp'], unique=False)
    op.create_index(op.f('ix_environment_temperature'), 'environment', ['temperature'], unique=False)
    op.create_index(op.f('ix_environment_source_timestamp'), 'environment', ['source_timestamp'], unique=False)
    op.create_index(op.f('ix_environment_smoke_value'), 'environment', ['smoke_value'], unique=False)
    op.create_index(op.f('ix_environment_smoke_threshold'), 'environment', ['smoke_threshold'], unique=False)
    op.create_index(op.f('ix_environment_smoke_detected'), 'environment', ['smoke_detected'], unique=False)
    op.create_index(op.f('ix_environment_room_mode'), 'environment', ['room_mode'], unique=False)
    op.create_index(op.f('ix_environment_message_id'), 'environment', ['message_id'], unique=False)
    op.create_index(op.f('ix_environment_humidity'), 'environment', ['humidity'], unique=False)
    op.create_index(op.f('ix_environment_gateway_received_timestamp'), 'environment', ['gateway_received_timestamp'], unique=False)
    op.create_index(op.f('ix_environment_environment_timestamp'), 'environment', ['environment_timestamp'], unique=False)
    op.create_index(op.f('ix_environment_environment_id'), 'environment', ['environment_id'], unique=False)
    op.create_index(op.f('ix_environment_co2'), 'environment', ['co2'], unique=False)
    op.create_index(op.f('ix_environment_air_quality'), 'environment', ['air_quality'], unique=False)
    op.create_index(op.f('ix_device_status_status_timestamp'), 'device_status', ['status_timestamp'], unique=False)
    op.create_index(op.f('ix_device_status_device_id'), 'device_status', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_heartbeat_source_timestamp'), 'device_heartbeat', ['source_timestamp'], unique=False)
    op.create_index(op.f('ix_device_heartbeat_message_id'), 'device_heartbeat', ['message_id'], unique=False)
    op.create_index(op.f('ix_device_heartbeat_heartbeat_timestamp'), 'device_heartbeat', ['heartbeat_timestamp'], unique=False)
    op.create_index(op.f('ix_device_heartbeat_gateway_received_timestamp'), 'device_heartbeat', ['gateway_received_timestamp'], unique=False)
    op.create_index(op.f('ix_device_heartbeat_device_heartbeat_id'), 'device_heartbeat', ['device_heartbeat_id'], unique=False)
    op.drop_index(op.f('ix_device_room_id'), table_name='device')
    op.create_index(op.f('ix_device_room_id'), 'device', ['room_id'], unique=True)
    op.create_index(op.f('ix_device_last_seen_timestamp'), 'device', ['last_seen_timestamp'], unique=False)
    op.create_index(op.f('ix_device_device_name'), 'device', ['device_name'], unique=False)
    op.create_index(op.f('ix_device_device_id'), 'device', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_device_firmware_version'), 'device', ['device_firmware_version'], unique=False)
    op.create_index(op.f('ix_attendance_statuses_status_name'), 'attendance_statuses', ['status_name'], unique=False)
    op.create_index(op.f('ix_attendance_statuses_description'), 'attendance_statuses', ['description'], unique=False)
    op.create_index(op.f('ix_attendance_statuses_attendance_status_id'), 'attendance_statuses', ['attendance_status_id'], unique=False)
    op.create_foreign_key(op.f('attendance_events_card_uid_fkey'), 'attendance_events', 'users', ['card_uid'], ['card_uid'])
    op.create_index(op.f('ix_attendance_events_source_timestamp'), 'attendance_events', ['source_timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_events_message_id'), 'attendance_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_gateway_received_timestamp'), 'attendance_events', ['gateway_received_timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_events_attendance_timestamp'), 'attendance_events', ['attendance_timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_events_attendance_event_id'), 'attendance_events', ['attendance_event_id'], unique=False)
    op.drop_index(op.f('ix_command_status'), table_name='command')
    op.drop_index(op.f('ix_command_room_id'), table_name='command')
    op.drop_index(op.f('ix_command_device_id'), table_name='command')
    op.drop_table('command')
    # ### end Alembic commands ###
