"""create Summarizer

Revision ID: 518593eef512
Revises: 0c13fde3643a
Create Date: 2026-09-15 14:23:00.062981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518593eef512'
down_revision: Union[str, Sequence[str], None] = '0c13fde3643a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_summarizer', sa.Column('raw_data', sa.String(), nullable=False))
    op.add_column('raw_summarizer', sa.Column('summary', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_summarizer', 'summary')
    op.drop_column('raw_summarizer', 'raw_data')
    # ### end Alembic commands ###
