"""initial schema

Revision ID: 560716a1684b
Revises: 
Create Date: 2026-08-18 14:18:16.296354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560716a1684b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_statuses',
    sa.Column('attendance_status_id', sa.String(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('attendance_status_id')
    )
    op.create_index(op.f('ix_attendance_statuses_attendance_status_id'), 'attendance_statuses', ['attendance_status_id'], unique=False)
    op.create_index(op.f('ix_attendance_statuses_description'), 'attendance_statuses', ['description'], unique=False)
    op.create_index(op.f('ix_attendance_statuses_status_name'), 'attendance_statuses', ['status_name'], unique=False)
    op.create_table('peripheral',
    sa.Column('peripheral_id', sa.UUID(), nullable=False),
    sa.Column('peripheral_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('peripheral_id')
    )
    op.create_table('room',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('room_type', sa.Enum('CLASSROOM', 'CORRIDOR', name='roomtype'), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_uid', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'LECTURER', 'STUDENT', 'UNKNOWN', name='userrole'), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_card_uid'), 'users', ['card_uid'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attendance_events',
    sa.Column('attendance_event_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('card_uid', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('CHECK_IN', 'CHECK_OUT', 'REJECT', name='attendanceeventtype'), nullable=True),
    sa.Column('attendance_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attendance_status_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('gateway_received_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_status_id'], ['attendance_statuses.attendance_status_id'], ),
    sa.ForeignKeyConstraint(['card_uid'], ['users.card_uid'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attendance_event_id', 'attendance_timestamp')
    )
    op.create_index(op.f('ix_attendance_events_attendance_event_id'), 'attendance_events', ['attendance_event_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_attendance_timestamp'), 'attendance_events', ['attendance_timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_events_card_uid'), 'attendance_events', ['card_uid'], unique=False)
    op.create_index(op.f('ix_attendance_events_event_type'), 'attendance_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_attendance_events_gateway_received_timestamp'), 'attendance_events', ['gateway_received_timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_events_message_id'), 'attendance_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_room_id'), 'attendance_events', ['room_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_source_timestamp'), 'attendance_events', ['source_timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_events_user_id'), 'attendance_events', ['user_id'], unique=False)
    op.create_table('classes',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('class_code', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('lecturer_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('class_created_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_classes_class_code'), 'classes', ['class_code'], unique=True)
    op.create_index(op.f('ix_classes_class_created_timestamp'), 'classes', ['class_created_timestamp'], unique=False)
    op.create_index(op.f('ix_classes_class_id'), 'classes', ['class_id'], unique=False)
    op.create_index(op.f('ix_classes_class_name'), 'classes', ['class_name'], unique=False)
    op.create_index(op.f('ix_classes_is_active'), 'classes', ['is_active'], unique=False)
    op.create_index(op.f('ix_classes_lecturer_id'), 'classes', ['lecturer_id'], unique=False)
    op.create_table('device',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('device_firmware_version', sa.String(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('device_status', sa.Enum('online', 'offline', name='devicestatusenum'), nullable=False),
    sa.Column('last_seen_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_device_device_firmware_version'), 'device', ['device_firmware_version'], unique=False)
    op.create_index(op.f('ix_device_device_id'), 'device', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_device_name'), 'device', ['device_name'], unique=False)
    op.create_index(op.f('ix_device_device_status'), 'device', ['device_status'], unique=False)
    op.create_index(op.f('ix_device_last_seen_timestamp'), 'device', ['last_seen_timestamp'], unique=False)
    op.create_index(op.f('ix_device_mac_address'), 'device', ['mac_address'], unique=True)
    op.create_index(op.f('ix_device_room_id'), 'device', ['room_id'], unique=True)
    op.create_table('environment',
    sa.Column('environment_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('smoke_detected', sa.Boolean(), nullable=False),
    sa.Column('smoke_value', sa.Float(), nullable=True),
    sa.Column('smoke_threshold', sa.Float(), nullable=True),
    sa.Column('smoke_state', sa.Enum('NORMAL', 'SUSPECTED', 'EMERGENCY', name='smokestate'), nullable=False),
    sa.Column('co2', sa.Integer(), nullable=True),
    sa.Column('air_quality', sa.Integer(), nullable=True),
    sa.Column('room_mode', sa.Enum('SAVING', 'SELF_STUDY', 'LECTURE', 'EXAM', 'LOCK', 'SUSPECTED', 'EMERGENCY', name='roommodeenum'), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('gateway_received_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('environment_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('environment_id', 'environment_timestamp')
    )
    op.create_index(op.f('ix_environment_air_quality'), 'environment', ['air_quality'], unique=False)
    op.create_index(op.f('ix_environment_co2'), 'environment', ['co2'], unique=False)
    op.create_index(op.f('ix_environment_environment_id'), 'environment', ['environment_id'], unique=False)
    op.create_index(op.f('ix_environment_environment_timestamp'), 'environment', ['environment_timestamp'], unique=False)
    op.create_index(op.f('ix_environment_gateway_received_timestamp'), 'environment', ['gateway_received_timestamp'], unique=False)
    op.create_index(op.f('ix_environment_humidity'), 'environment', ['humidity'], unique=False)
    op.create_index(op.f('ix_environment_message_id'), 'environment', ['message_id'], unique=False)
    op.create_index(op.f('ix_environment_room_id'), 'environment', ['room_id'], unique=False)
    op.create_index(op.f('ix_environment_room_mode'), 'environment', ['room_mode'], unique=False)
    op.create_index(op.f('ix_environment_smoke_detected'), 'environment', ['smoke_detected'], unique=False)
    op.create_index(op.f('ix_environment_smoke_state'), 'environment', ['smoke_state'], unique=False)
    op.create_index(op.f('ix_environment_smoke_threshold'), 'environment', ['smoke_threshold'], unique=False)
    op.create_index(op.f('ix_environment_smoke_value'), 'environment', ['smoke_value'], unique=False)
    op.create_index(op.f('ix_environment_source_timestamp'), 'environment', ['source_timestamp'], unique=False)
    op.create_index(op.f('ix_environment_temperature'), 'environment', ['temperature'], unique=False)
    op.create_table('occupancy',
    sa.Column('occupancy_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('occupancy_type', sa.Enum('IN', 'OUT', name='irsignaltype'), nullable=True),
    sa.Column('occupancy_count', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('gateway_received_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('occupancy_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('occupancy_id', 'occupancy_timestamp')
    )
    op.create_index(op.f('ix_occupancy_gateway_received_timestamp'), 'occupancy', ['gateway_received_timestamp'], unique=False)
    op.create_index(op.f('ix_occupancy_message_id'), 'occupancy', ['message_id'], unique=False)
    op.create_index(op.f('ix_occupancy_occupancy_count'), 'occupancy', ['occupancy_count'], unique=False)
    op.create_index(op.f('ix_occupancy_occupancy_id'), 'occupancy', ['occupancy_id'], unique=False)
    op.create_index(op.f('ix_occupancy_occupancy_timestamp'), 'occupancy', ['occupancy_timestamp'], unique=False)
    op.create_index(op.f('ix_occupancy_occupancy_type'), 'occupancy', ['occupancy_type'], unique=False)
    op.create_index(op.f('ix_occupancy_room_id'), 'occupancy', ['room_id'], unique=False)
    op.create_index(op.f('ix_occupancy_source_timestamp'), 'occupancy', ['source_timestamp'], unique=False)
    op.create_table('peripheral_action',
    sa.Column('peripheral_action_id', sa.UUID(), nullable=False),
    sa.Column('peripheral_id', sa.UUID(), nullable=False),
    sa.Column('peripheral_action_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripheral.peripheral_id'], ),
    sa.PrimaryKeyConstraint('peripheral_action_id')
    )
    op.create_table('room_state',
    sa.Column('room_state_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('room_state_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_mode', sa.Enum('SAVING', 'SELF_STUDY', 'LECTURE', 'EXAM', 'LOCK', 'SUSPECTED', 'EMERGENCY', name='roommodeenum'), nullable=False),
    sa.Column('room_status', sa.Enum('online', 'offline', name='roomstatus'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('room_state_id', 'room_state_timestamp')
    )
    op.create_index(op.f('ix_room_state_room_mode'), 'room_state', ['room_mode'], unique=False)
    op.create_table('class_enrollments',
    sa.Column('enrollment_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id'),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_class_enrollment_student')
    )
    op.create_index(op.f('ix_class_enrollments_class_id'), 'class_enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_enrollments_enrollment_id'), 'class_enrollments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_class_enrollments_enrollment_timestamp'), 'class_enrollments', ['enrollment_timestamp'], unique=False)
    op.create_index(op.f('ix_class_enrollments_is_active'), 'class_enrollments', ['is_active'], unique=False)
    op.create_index(op.f('ix_class_enrollments_student_id'), 'class_enrollments', ['student_id'], unique=False)
    op.create_table('device_heartbeat',
    sa.Column('device_heartbeat_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('gateway_received_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('heartbeat_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.PrimaryKeyConstraint('device_heartbeat_id', 'heartbeat_timestamp')
    )
    op.create_index(op.f('ix_device_heartbeat_device_heartbeat_id'), 'device_heartbeat', ['device_heartbeat_id'], unique=False)
    op.create_index(op.f('ix_device_heartbeat_device_id'), 'device_heartbeat', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_heartbeat_gateway_received_timestamp'), 'device_heartbeat', ['gateway_received_timestamp'], unique=False)
    op.create_index(op.f('ix_device_heartbeat_heartbeat_timestamp'), 'device_heartbeat', ['heartbeat_timestamp'], unique=False)
    op.create_index(op.f('ix_device_heartbeat_message_id'), 'device_heartbeat', ['message_id'], unique=False)
    op.create_index(op.f('ix_device_heartbeat_source_timestamp'), 'device_heartbeat', ['source_timestamp'], unique=False)
    op.create_table('device_status',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('device_status', sa.Enum('online', 'offline', name='devicestatusenum'), nullable=False),
    sa.Column('status_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_device_status_device_id'), 'device_status', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_status_device_status'), 'device_status', ['device_status'], unique=False)
    op.create_index(op.f('ix_device_status_status_timestamp'), 'device_status', ['status_timestamp'], unique=False)
    op.create_table('room_event',
    sa.Column('room_event_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('room_event_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_mode', sa.Enum('SAVING', 'SELF_STUDY', 'LECTURE', 'EXAM', 'LOCK', 'SUSPECTED', 'EMERGENCY', name='roommodeenum'), nullable=False),
    sa.Column('peripheral_action_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['peripheral_action_id'], ['peripheral_action.peripheral_action_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('room_event_id', 'room_event_timestamp')
    )
    op.create_index(op.f('ix_room_event_room_mode'), 'room_event', ['room_mode'], unique=False)
    op.create_table('room_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('class_code', sa.String(), nullable=True),
    sa.Column('session_start_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attendance_deadline_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('session_end_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_exam', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_room_sessions_attendance_deadline_timestamp'), 'room_sessions', ['attendance_deadline_timestamp'], unique=False)
    op.create_index(op.f('ix_room_sessions_class_code'), 'room_sessions', ['class_code'], unique=False)
    op.create_index(op.f('ix_room_sessions_class_id'), 'room_sessions', ['class_id'], unique=False)
    op.create_index(op.f('ix_room_sessions_is_exam'), 'room_sessions', ['is_exam'], unique=False)
    op.create_index(op.f('ix_room_sessions_lecturer_id'), 'room_sessions', ['lecturer_id'], unique=False)
    op.create_index(op.f('ix_room_sessions_room_id'), 'room_sessions', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_sessions_session_end_timestamp'), 'room_sessions', ['session_end_timestamp'], unique=False)
    op.create_index(op.f('ix_room_sessions_session_id'), 'room_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_room_sessions_session_start_timestamp'), 'room_sessions', ['session_start_timestamp'], unique=False)
    op.create_table('attendance_records',
    sa.Column('attendance_record_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('card_uid', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('attendance_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_uid'], ['users.card_uid'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['room_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attendance_record_id'),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_attendance_session_user')
    )
    op.create_index(op.f('ix_attendance_records_attendance_record_id'), 'attendance_records', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_attendance_timestamp'), 'attendance_records', ['attendance_timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_records_card_uid'), 'attendance_records', ['card_uid'], unique=False)
    op.create_index(op.f('ix_attendance_records_late'), 'attendance_records', ['late'], unique=False)
    op.create_index(op.f('ix_attendance_records_room_id'), 'attendance_records', ['room_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_user_id'), 'attendance_records', ['user_id'], unique=False)
    
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE")

    op.execute("SELECT create_hypertable('attendance_events', by_range('attendance_timestamp'), if_not_exists => TRUE)")
    op.execute("SELECT create_hypertable('environment', by_range('environment_timestamp'), if_not_exists => TRUE)")
    op.execute("SELECT create_hypertable('occupancy', by_range('occupancy_timestamp'), if_not_exists => TRUE)")
    op.execute("SELECT create_hypertable('device_heartbeat', by_range('heartbeat_timestamp'), if_not_exists => TRUE)")
    op.execute("SELECT create_hypertable('room_state', by_range('room_state_timestamp'), if_not_exists => TRUE)")
    op.execute("SELECT create_hypertable('room_event', by_range('room_event_timestamp'), if_not_exists => TRUE)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_user_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_room_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_late'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_card_uid'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_timestamp'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_record_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_room_sessions_session_start_timestamp'), table_name='room_sessions')
    op.drop_index(op.f('ix_room_sessions_session_id'), table_name='room_sessions')
    op.drop_index(op.f('ix_room_sessions_session_end_timestamp'), table_name='room_sessions')
    op.drop_index(op.f('ix_room_sessions_room_id'), table_name='room_sessions')
    op.drop_index(op.f('ix_room_sessions_lecturer_id'), table_name='room_sessions')
    op.drop_index(op.f('ix_room_sessions_is_exam'), table_name='room_sessions')
    op.drop_index(op.f('ix_room_sessions_class_id'), table_name='room_sessions')
    op.drop_index(op.f('ix_room_sessions_class_code'), table_name='room_sessions')
    op.drop_index(op.f('ix_room_sessions_attendance_deadline_timestamp'), table_name='room_sessions')
    op.drop_table('room_sessions')
    op.drop_index(op.f('ix_room_event_room_mode'), table_name='room_event')
    op.drop_table('room_event')
    op.drop_index(op.f('ix_device_status_status_timestamp'), table_name='device_status')
    op.drop_index(op.f('ix_device_status_device_status'), table_name='device_status')
    op.drop_index(op.f('ix_device_status_device_id'), table_name='device_status')
    op.drop_table('device_status')
    op.drop_index(op.f('ix_device_heartbeat_source_timestamp'), table_name='device_heartbeat')
    op.drop_index(op.f('ix_device_heartbeat_message_id'), table_name='device_heartbeat')
    op.drop_index(op.f('ix_device_heartbeat_heartbeat_timestamp'), table_name='device_heartbeat')
    op.drop_index(op.f('ix_device_heartbeat_gateway_received_timestamp'), table_name='device_heartbeat')
    op.drop_index(op.f('ix_device_heartbeat_device_id'), table_name='device_heartbeat')
    op.drop_index(op.f('ix_device_heartbeat_device_heartbeat_id'), table_name='device_heartbeat')
    op.drop_table('device_heartbeat')
    op.drop_index(op.f('ix_class_enrollments_student_id'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_is_active'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_enrollment_timestamp'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_enrollment_id'), table_name='class_enrollments')
    op.drop_index(op.f('ix_class_enrollments_class_id'), table_name='class_enrollments')
    op.drop_table('class_enrollments')
    op.drop_index(op.f('ix_room_state_room_mode'), table_name='room_state')
    op.drop_table('room_state')
    op.drop_table('peripheral_action')
    op.drop_index(op.f('ix_occupancy_source_timestamp'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_room_id'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_occupancy_type'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_occupancy_timestamp'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_occupancy_id'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_occupancy_count'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_message_id'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_gateway_received_timestamp'), table_name='occupancy')
    op.drop_table('occupancy')
    op.drop_index(op.f('ix_environment_temperature'), table_name='environment')
    op.drop_index(op.f('ix_environment_source_timestamp'), table_name='environment')
    op.drop_index(op.f('ix_environment_smoke_value'), table_name='environment')
    op.drop_index(op.f('ix_environment_smoke_threshold'), table_name='environment')
    op.drop_index(op.f('ix_environment_smoke_state'), table_name='environment')
    op.drop_index(op.f('ix_environment_smoke_detected'), table_name='environment')
    op.drop_index(op.f('ix_environment_room_mode'), table_name='environment')
    op.drop_index(op.f('ix_environment_room_id'), table_name='environment')
    op.drop_index(op.f('ix_environment_message_id'), table_name='environment')
    op.drop_index(op.f('ix_environment_humidity'), table_name='environment')
    op.drop_index(op.f('ix_environment_gateway_received_timestamp'), table_name='environment')
    op.drop_index(op.f('ix_environment_environment_timestamp'), table_name='environment')
    op.drop_index(op.f('ix_environment_environment_id'), table_name='environment')
    op.drop_index(op.f('ix_environment_co2'), table_name='environment')
    op.drop_index(op.f('ix_environment_air_quality'), table_name='environment')
    op.drop_table('environment')
    op.drop_index(op.f('ix_device_room_id'), table_name='device')
    op.drop_index(op.f('ix_device_mac_address'), table_name='device')
    op.drop_index(op.f('ix_device_last_seen_timestamp'), table_name='device')
    op.drop_index(op.f('ix_device_device_status'), table_name='device')
    op.drop_index(op.f('ix_device_device_name'), table_name='device')
    op.drop_index(op.f('ix_device_device_id'), table_name='device')
    op.drop_index(op.f('ix_device_device_firmware_version'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_classes_lecturer_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_is_active'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_created_timestamp'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_code'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_attendance_events_user_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_source_timestamp'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_room_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_message_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_gateway_received_timestamp'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_event_type'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_card_uid'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_attendance_timestamp'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_attendance_event_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_card_uid'), table_name='users')
    op.drop_table('users')
    op.drop_table('room')
    op.drop_table('peripheral')
    op.drop_index(op.f('ix_attendance_statuses_status_name'), table_name='attendance_statuses')
    op.drop_index(op.f('ix_attendance_statuses_description'), table_name='attendance_statuses')
    op.drop_index(op.f('ix_attendance_statuses_attendance_status_id'), table_name='attendance_statuses')
    op.drop_table('attendance_statuses')
    # ### end Alembic commands ###
